### ISSUE TITLE
Bug? Can't generate batches using dynamic prompting v0.4.3

### ISSUE THREAD

**Issue by trihardseven** [adieyal/sd-dynamic-prompting#10]
Increasing batch size does nothing with this script on. Tried using no wildcards, reducing size of image, different samplers, etc. The only thing that makes batch size work again is turning off the script. Batch size increases overall speed of generating many images in cards with lots of vram so it's very useful.

I have a 3090 using voldy commit hash f49c08ea566385db339c6628f65c3a121033f67c

**Comment by adieyal** [comment]
I just tested on my end - batches work fine. Do you get an error message?

**Comment by trihardseven** [comment]
no error, but it says "Prompt matrix will create 1 images using a total of 1 batches."
when the script isn't active it doesn't say that

**Comment by adieyal** [comment]
What if you choose batch count 8, batch size 4?

**Comment by trihardseven** [comment]
Nothing changes, still the same message too. Disabling the script and not changing anything else makes it batch 8 files

**Comment by trihardseven** [comment]
Also other scripts like X/Y plot seem to work fine with batch too

**Comment by adieyal** [comment]
I'm trying to reproduce your issue. Have a look at these screenshots, are your settings the same as mine?
![Screenshot from 2022-10-22 11-28-02](https://user-images.githubusercontent.com/420786/197329569-772597e1-eec6-4ee8-aa1d-2a7c05363d7f.png)

![Screenshot from 2022-10-22 11-30-23](https://user-images.githubusercontent.com/420786/197329616-cb96b762-e396-40a3-9f9c-9a8ab9e82031.png)

**Comment by trihardseven** [comment]
Ah, I misread your comment. I thought you said to try batch size 4 and then 8. Doing it with your settings worked, thanks.

**Comment by adieyal** [comment]
There is a bug, i.e. batch count is currently defined as num images whereas it should simply be the number of batches. I'll fix that, but I wanted to make sure there wasn't another issue.

**Comment by adieyal** [comment]
Fixed - it should now work the same way as the rest of the tool
