### ISSUE TITLE
Reiteration of the wildcards

### ISSUE THREAD

**Issue by aniketgore** [adieyal/sd-dynamic-prompting#11]
Loving this script. Is there a way to reiterate wildcards one by one?

**Comment by adieyal** [comment]
Glad you're finding it useful. Could you elaborate on what you mean by reiterate?

**Comment by aniketgore** [comment]
so if we have a txt file obj like below, and my prompt is photo of __obj__

obj1
obj2
..
..
..
obj99

I want to let the sd iterate through the 99 obj, and generate 99 images of the photo of __obj__ each with different obj.

**Comment by adieyal** [comment]
@evanjs, I hope you don't mind me pulling you into this. I was wondering whether you thought this request was in scope for the script. Currently it generates random prompts from wildcard files and inline combinations. @aniketgore is requesting something that looks more like a batch process. I'm on the fence about this one. Here's a possible implementation:

    A photo of __obj*__

Here I'm using `__wildcard*__` to mean generating one prompt for every row in the file. 
You could then presumably have two or more of these in the same prompt, e.g.:

    A photo of __obj*__ and __obj2*__

That would generate len(obj) * len(obj2) images.

In this case, we would need to ignore the number batches setting in the ui.

Curious about your thoughts.

**Comment by evanjs** [comment]
I think I am also on the fence.

While I do have it listed under "controverisal additions" in my [PR](https://github.com/adieyal/sd-dynamic-prompting/pull/15), I had been using `*` for globbing wildcard paths.

As you mentioned, we currently only use dynamic prompt expressions to influence what is _in_ the prompt.
If we use `*` to expand/choose all terms in a file, I have to wonder how a few things would work.

As mentioned, we would need to either ignore batch count, or treat it similar to X/Y prompting.
e.g. "Do 2 batches of A: 1,2,3 B: 4,5,6"

But how would this interact with combinations, for example?

e.g. what would be the result of `{obj*|obj*}`?

**Comment by Koronos** [comment]
Can I suggest the usage of a dolble brances for generation? this could help to generate more prompts from a choice something like:

`A great school at night with a {{ squirrel,dog }}`

This would generate 2 prompts, and with the wildcard could be equal:

`A great school at {{__day-time__}} with a {{ squirrel,dog }}`

if __day-time__ contains Day and Night, this would generate 4 at 1 batch: x - day time, y - animal. 

By the way, about the result of `{obj*|obj*}`. Is like this case:

`A great {{__place__}} at {{__day-time__}} with a {{ squirrel,dog }}`

I think that just do the exponential generation and generate a big grid with the params separated by comma at bottom of each file, something like this:

![image](https://user-images.githubusercontent.com/7765638/197663157-b47f3199-396c-45c4-9b5b-85dfc644bddb.png)

What do you think?

**Comment by adieyal** [comment]
Here is an initial implementation of this. https://github.com/adieyal/sd-dynamic-prompting/tree/feature/exhaustive-generation - I haven't implemented combinations yet, i.e. `{2$$a|b|c}`. Let me know what you think.

**Comment by Xyem** [comment]
Just to mention, `reiteration` is to repeat something. I think the term you were looking for is `enumerate` (to go through, one by one).

I would also find this quite useful, if implemented.

**Comment by adieyal** [comment]
> 
> I would also find this quite useful, if implemented.

@Xyem you should have a look at this WIP -  https://github.com/adieyal/sd-dynamic-prompting/tree/feature/exhaustive-generation
