### ISSUE TITLE
Scan wildcards directory recursively

### ISSUE THREAD

**Issue by evanjs** [adieyal/sd-dynamic-prompting#12]
With a large number of wildcards, it can be unwieldy to maintain several large files in a single directory.
It would be nice if this script could scan recursively for wildcards in file structures of arbitrary depth.

[Here ](https://github.com/evanjs/sd-dynamic-prompting/blob/7e9f7d1edce0cd38b8effee0a4b44b9220188466/dynamic_prompting.py#L63-L99)is how I am handling it in my repository, using <span><code><a href="https://docs.python.org/3/library/pathlib.html#pathlib.Path.rglob">rglob</a></code></span>.

Also note that other repositories such as [a1111-sd-webui-tagcomplete](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete) have already [implemented](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/commit/5bf045143208dd00f1f8c184833b70751b0f78d6) support for this feature; a similar update to dynamic prompting would complement this nicely.

To help improve readability, I also [changed](https://github.com/evanjs/sd-dynamic-prompting/blob/7e9f7d1edce0cd38b8effee0a4b44b9220188466/dynamic_prompting.py#L151-L152) the script text element to display paths relative to `WILDCARD_DIR`, and [made the list scrollable](https://github.com/evanjs/sd-dynamic-prompting/blob/7e9f7d1edce0cd38b8effee0a4b44b9220188466/dynamic_prompting.py#L148), to prevent a large number of wildcard files from expanding the page uncontrollably.

Happy to make a PR if the use case is valid and the changes (or something similar) sound acceptable.

**Comment by adieyal** [comment]
Sounds good - send through a PR and I'll merge it.
