### ISSUE TITLE
"Person" wildcard also drew from "personaction" wildcard

### ISSUE THREAD

**Issue by Adil3tr** [adieyal/sd-dynamic-prompting#18]
I had a person wildcard with three names, but when I used it, I was getting images with prompts like "through a window," and "in space" and I realized it was taking from both the __person__ wildcard and the __personaction__ wildcard. I haven't noticed this until I updated to the .5 version of this script.

**Comment by adieyal** [comment]
I think I know what's happening there. It should be fixed in the next release. If you like, you can test the path globbing branch - https://github.com/adieyal/sd-dynamic-prompting/tree/feature/path-globbing

**Comment by adieyal** [comment]
I've pushed 0.6.0 to main which should resolve this. Re-open this issue if the same issue crops up again.
