### ISSUE TITLE
Dynamic Prompting extension?

### ISSUE THREAD

**Issue by Skalinos** [adieyal/sd-dynamic-prompting#19]
Love the script! Question - is it possible to adapt Dynamic Prompting into an extension?

**Comment by adieyal** [comment]
Glad you're enjoying it. It's on the to do list. Thanks for opening the issue.

**Comment by adieyal** [comment]
Released as an extension - https://github.com/adieyal/sd-dynamic-prompting/tree/v0.11.0 - let me know if you encounter any issues.
