### ISSUE TITLE
Wildcard progressive autocomplete

### ISSUE THREAD

**Issue by Xyem** [adieyal/sd-dynamic-prompting#20]
I do apologise if this is the wrong place as I'm not sure what implements this, but when writing a prompt, I can use the tab key to autocomplete wildcards. This is very useful, except it will auto-complete whichever one is the top one, rather than filling in only what is "common" to the current possibilities. This means I have to type out a considerable amount before I can auto-complete usefully.

For example, if the three files are "foofoo", "foobar" and "foobaz". I would expect the following:

1. `f<TAB>` becomes "foo"
2. `foob<TAB>` becomes "fooba"

Currently, `f<TAB>` would just autocomplete whichever happens to be first in the list of possibilities.

**Comment by evanjs** [comment]
I am not sure if this library implements or interacts with auto-completion
Are you thinking of https://github.com/DominikDoom/a1111-sd-webui-tagcomplete, by any chance?

**Comment by Xyem** [comment]
Yes! Sorry, I thought that only provided tag auto-completion but I just checked the commit history and they added in wildcard support, so that's where it is coming from. Please excuse the noise!
