### ISSUE TITLE
How to use it as an extension?

### ISSUE THREAD

**Issue by walklty** [adieyal/sd-dynamic-prompting#22]
Many thanks to see there are many updates recently.
I see the script are changed into an extension since 0.11.
But the UI is still in the "script" drop-down menu. Maybe it should move to the setting page？

I want to use it with an other script to run repeatly, but currently the Combinatorial mode is not working with batchs.

**Comment by adieyal** [comment]
Regarding the extension - there isn't a ton of documentation available. My understanding was that the main change between extensions and scripts was that you weren't restricted to a single script file and that your javascript and css was automatically added to the rest of the app. How would you expect it to work? 

Re batches, could you give me more information? I tested running with batches on my side and got the expected results.

**Comment by walklty** [comment]
In Combinatorial mode, it will create maxium batch count*size.
Then I want to repeat it n times with random seeds.

if n=2, i get
seed1:
Winter is coming
Summer is coming
seed2:
Winter is coming
Summer is coming

**Comment by adieyal** [comment]
I think that's the expected behaviour. There is no randomness in combinatorial, It simply creates every possible variation up to a maximum of batch_count * batch_size. If you keep re-running it, the prompts will be the same, but the images should be different.

Is that we're you're seeing?

**Comment by walklty** [comment]
Yes, but I mean, I don't want to manually re-run it n times. Maybe there can be an input in the ui for repeating n times.

**Comment by adieyal** [comment]
gotcha - sure, I'll add that.

**Comment by adieyal** [comment]
Can you give 0.12.0 a whirl

**Comment by walklty** [comment]
Working. Thank you very much
