### ISSUE TITLE
Nested dynamic prompting?

### ISSUE THREAD

**Issue by tusharbhutt** [adieyal/sd-dynamic-prompting#8]
I'd like to try something like this

A {male|female} {elf|orc|goblin} {warrior|priest|wizard} {walking in the {forest|desert}|running in the {jungle|arctic}}

but the script does not give me the alternatives at the end. I end up with results like:

A female elf priest {walking in the forest|running in the arctic}  ... so it's picking the variables but not recursively picking the setting.  Is that possible to do?

Thanks,

TB

**Comment by adieyal** [comment]
That sort of nesting is not possible using regular expressions which is what I am using to parse the prompts. A more sophisticated parser would be needed. I'll look into it. In the meanwhile, there is a workaround.

You can nest `__wildcards__` inside `{}` and you can nest `{}` inside `__wildcards__`

So, for example, something like this:

`A {male|female} {elf|orc|goblin} {warrior|priest|wizard} {walking in the __biome__|running in the __biome2__}`

Then create biome.txt containing:

    forest
    desert

and biome2.txt containing:

    jungle
    arctic

place those files into `WILDCARD_DIR` which is usually in scripts/wildcards.

Alternatively:

    `A {male|female} {elf|orc|goblin} {warrior|priest|wizard} __actions__`

Then create actions.txt like so:

    walking in the {forest|desert}
    running in the {jungle|arctic}

In most cases, this should be a good alternative. Let me know if that works for you.

**Comment by tusharbhutt** [comment]
> That sort of nesting is not possible using regular expressions which is what I am using to parse the prompts. A more sophisticated parser would be needed. I'll look into it. In the meanwhile, there is a workaround.
> 
> You can nest `__wildcards__` inside `{}` and you can nest `{}` inside `__wildcards__`
[...]
> In most cases, this should be a good alternative. Let me know if that works for you.

Thank you so much I will give that a try.  No need to reprogram the script for something RegEx won't do :)

**Comment by axemaster** [comment]
> You can nest `__wildcards__` inside `{}` and you can nest `{}` inside `__wildcards__`

I do this and it works great. I do love this extension.

**Comment by designosis** [comment]
Is this still the case?
Or does `{ (thing1:{1|1.5|2}) | (thing2:{0.3|0.6|1}) }` work now?

**Comment by designosis** [comment]
Ping ...

**Comment by akx** [comment]
@designosis 

> Or does `{ (thing1:{1|1.5|2}) | (thing2:{0.3|0.6|1}) }` work now?

If the idea is to vary the strengths of those prompt fragments, that does indeed work. In combinatorial mode, this generates the prompts

```json
["(red:1) ", "(red:1.5) ", "(red:2) ", "(green:0.3) ", "(green:0.6) ", "(green:1) "]
```

> Ping ...

You could've just tried this out yourself instead of having to wait for a month 😅
