### ISSUE TITLE
Display unprocessed prompt with wildcards alongside processed prompt

### ISSUE THREAD

**Issue by evanjs** [adieyal/sd-dynamic-prompting#9]
In [jtkelm's wildcards script](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Custom-Scripts#wildcards) (repo link seems to be dead, but it should be similar to [this](https://github.com/evanjs/stable-diffusion-webui/blob/1e2f86dfd54be756ee30dd489358640bf3356740/scripts/wildcards.py#L1)), prompts are displayed both raw and unprocessed in the dialog box.
* Wildcard prompt: The raw text before it has been processed. This includes wildcards used
  * e.g. `__season__`
* Example: the processed prompt, with wildcards replaced with the selection for each item
  * e.g. `winter`
* Negative: `unmodified negative prompt`

While it might not be as helpful in "Generate forever" sessions without ensuring the wildcards are also exported, it could be helpful for single generations, and can help the user ensure their expressions are working as intended.

Though, after thinking on it, I wonder what we'd choose to display if this was implemented, since dynamic prompting allows for combinations and options.
Would we display the initial raw prompt without _any_ evaluation?
What about recursive wildcard evaluation? Would that make this feature less useful?

**Comment by adieyal** [comment]
Is there any benefit to displaying the raw prompt again, since it's already in the prompt box? As of 0.4.2, prompt resolution is recursive, i.e. you can have dynamic prompts inside wildcard files. If a user decides to have multiple levels of recursion, there might be a case for:
1. Display the raw prompt
2. Process options and display
3. Process wildcards and display
4. If the prompt still has dynamic elements, go to 2

I'm not sure if that's a real use case though.

**Comment by tusharbhutt** [comment]
@evanjs You're seeing the output of Wildcards in the output box?  Interesting, I had them disappear two days ago and was going to contact the author, but the script is gone :(

**Comment by evanjs** [comment]
> @evanjs You're seeing the output of Wildcards in the output box? Interesting, I had them disappear two days ago and was going to contact the author, but the script is gone :(

Yes, the author has since ensured the link is not dead, but provides a statement in the readme pointing others to this repository instead.
It should be similar to the script here: https://github.com/evanjs/stable-diffusion-webui/blob/5230e4eddc54932f899c9769cbbce585830d0311/scripts/wildcards.py

**Comment by evanjs** [comment]
> Is there any benefit to displaying the raw prompt again, since it's already in the prompt box? As of 0.4.2, prompt resolution is recursive, i.e. you can have dynamic prompts inside wildcard files. If a user decides to have multiple levels of recursion, there might be a case for:
> 
> 1. Display the raw prompt
> 2. Process options and display
> 3. Process wildcards and display
> 4. If the prompt still has dynamic elements, go to 2
> 
> I'm not sure if that's a real use case though.

Yeah, after thinking on it, showing the raw prompt might not be as helpful (unless the user has since made changes)

Showing choices (before and/or after evaluation) might be a more practical use case, but the biggest question I have at that point would be: "how much do we show and evaluate?"
Like, do we evaluate the entire chain and show _everything_, before and after?

I can see how that would get verbose pretty quickly, even if we did make the output scrollable.

**Comment by adieyal** [comment]
Do you have a use case for this? I don't understand the problem that it would solve.

**Comment by adieyal** [comment]
Should this issue be closed or is it worth discussing further?

**Comment by evanjs** [comment]
I think it's probably fair to close for now and reopen if valid use cases are brought up in the future.
